apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus
  labels:
    app: event-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: event-bus
        image: event-bus:latest
        imagePullPolicy: Never
        ports:
        - name: event-bus
          protocol: TCP
          containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-clusterip
spec:
  type: ClusterIP
  selector:
    app: event-bus
  ports:
  - name: event-bus-clusterip
    protocol: TCP
    port: 4005
    targetPort: 4005
