apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  labels:
    app: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: posts:latest
        imagePullPolicy: Never
        ports:
        - name: posts
          protocol: TCP
          containerPort: 4000
