apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
  labels:
    app: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
      - name: query
        image: query:latest
        imagePullPolicy: Never
        ports:
        - name: query
          protocol: TCP
          containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: query-clusterip
spec:
  type: ClusterIP
  selector:
    app: query
  ports:
  - name: query-clusterip
    protocol: TCP
    port: 4002
    targetPort: 4002
